### ISSUE TITLE
Nodejs  Issue ???

### ISSUE THREAD

**Issue by Kampouse** [fluentci-io/fluentci_feedback#1]
trying to run the base  nodejs template getting some issue when run with the cli with studio run well??  I will try on other computer but currently running into this 
<img width="868" alt="image" src="https://github.com/user-attachments/assets/89a76c58-5f46-4f46-9898-552aa14e1616">

**Comment by Kampouse** [comment]
tried with bun nodejs deno all af the same issue the only one working right now was the  wasm one

**Comment by tsirysndr** [comment]
Hi @Kampouse , thanks for reporting this issue!

It seems that this is caused by recent updates to the Dagger API, which removed the deprecated pipeline query. I'm currently working on updating the module to align with these changes. I'll be publishing a new version soon that should resolve this problem.
